#Will only run gc when tick used percentage is lower or equal to given value (default 10).
trigger-percentage: 10
#Will cancel gc if gc may exceed server tick time.
avoid-time-exceed: true
#Will only run gc when player count is 0 (default true).
trigger-no-player: true
#Will run gc unconditionally if root count exceeds the given value (default 500000).
force-root-count: 500000
#Will skip gc if root count increment is lower than the given ratio.
gc-skip-threshold-ratio: 0.02
#Prediction EMA(Exponential Moving Average) smoothing factor (default 0.3).
#The smoothing factor determines the weight given to the most recent data points.
#It controls how sensitive the EMA is to recent changes in the data.
smoothing-factor: 0.5